#!/usr/bin/perl

use strict;
use warnings;

use Device::Chip::Adapter;
use FindBin::libs;
use Device::Chip::TMP102;

use feature 'say';

my $ADAPTER     = "LinuxKernel";
my $MOUNTPARAMS = 'bus=/dev/i2c-1,addr=0x48';

my $sensor = Device::Chip::TMP102->new;

$sensor->mount_from_paramstr(
    Device::Chip::Adapter->new_from_description($ADAPTER), $MOUNTPARAMS, )->get;

my $config = $sensor->read_config->get;

#$sensor->change_config(
#    F => 4,
#)->get;

#$config = $sensor->read_config->get;

say Dumper($config);

my $temp = $sensor->read_temp->get;
print "Temp:\n";
printf ( "\t%2.2f C\n", $temp );
printf ( "\t%2.2f F\n", $temp * 1.8 + 32 );

